alias go='cd ~/mycode'
alias perm='chmod u+x *'
alias st='cd ~/mycode; git status'
alias add='cd ~/mycode; git add *'
alias psh='cd ~/mycode; git push origin main'
alias pll='cd ~/mycode; git pull origin main'
